WEB2021Apr_P04_T6/Models/CompetitionScore.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace WEB2021Apr_P04_T6.Models
{
    public class CompetitionScore
    {
        public int CriteriaID { get; set; }

        public int CompetitorID { get; set; }

        public int CompetitionID { get; set; }

        [Range(0, 10, ErrorMessage =
        "Invalid value! Please enter a value from 0 to 10")]
        public int Score { get; set; }

        public CompetitionScore() { }

        public CompetitionScore (int comp, int id)
        {
            CompetitionID = comp;
            CompetitorID = id;
        }
    }
}

WEB2021Apr_P04_T6/Controllers/CompetitionScoreController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WEB2021Apr_P04_T6.DAL;
using WEB2021Apr_P04_T6.Models;

namespace WEB2021Apr_P04_T6.Controllers
{
    public class CompetitionScoreController : Controller
    {
        private CompetitionScoreDAL competitionScoreContext = new CompetitionScoreDAL();
        private CompetitionDAL competitionContext = new CompetitionDAL();
        private CriteriaDAL criteriaContext = new CriteriaDAL();

        // GET: CompetitionScore
        public ActionResult Index(int? id, int? compid)
        {
            // Stop accessing the action if not logged in
            // or account not in the "Judge" role
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Judge"))
            {
                return RedirectToAction("Index", "Home");
            }
            SubmissionScoreViewModel competitionScoreViewModel = new SubmissionScoreViewModel();
            competitionScoreViewModel.submissionList = competitionScoreContext.GetCompetitionSubmissions();
            if (id != null)
            {
                ViewData["selectedCompetitor"] = id.Value;
                ViewData["selectedCompetition"] = compid.Value;
                // Get list of scores for competitor
                competitionScoreViewModel.scoreList = competitionScoreContext.GetCompetitorScores(compid.Value, id.Value);
            }
            else
            {
                ViewData["selectedCompetitor"] = "";
            }
            return View(competitionScoreViewModel);
        }

        private List<CompetitionSubmission> GetCompetitionSubmissions()
        {
            List<CompetitionSubmission> rCompetitionSubmissionsList = new List<CompetitionSubmission>();
            foreach (CompetitionSubmission comSub in competitionScoreContext.GetCompetitionSubmissions())
            {
                foreach (CompetitionJudge cJudge in GetRelatedCompetitions())
                {
                    if (comSub.CompetitionID == cJudge.CompetitionID)
                    {
                        rCompetitionSubmissionsList.Add(comSub);
                    }
                }
            }
            return rCompetitionSubmissionsList;
        }
        private List<CompetitionJudge> GetRelatedCompetitions()
        {
            List<CompetitionJudge> rCompetitionsList = new List<CompetitionJudge>();
            foreach (CompetitionJudge cJudge in competitionContext.GetCompetitionJudges())
            {
                if (cJudge.JudgeID == HttpContext.Session.GetInt32("JudgeID"))
                {
                    rCompetitionsList.Add(cJudge);
                }
            }
            return rCompetitionsList;
        }

        // GET: CompetitionScore/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: CompetitionScore/Create
        public ActionResult Create(string id, string comp)
        {
            // Stop accessing the action if not logged in
            // or account not in the "Judge" role
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Judge"))
            {
                return RedirectToAction("Index", "Home");
            }
            CompetitionScore competitionScore = new CompetitionScore(Int32.Parse(comp), Int32.Parse(id));
            ViewData["CriteriaID"] = GetRemainingCriterias(Int32.Parse(comp), Int32.Parse(id));
            return View(competitionScore);
        }

        // POST: CompetitionScore/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CompetitionScore competitionScore)
        {
            if (competitionContext.GetDetails(competitionScore.CompetitionID).ResultReleasedDate < DateTime.Now)
            {
                TempData["CompScoreCreateErrorMessage"] = "Results have already been released for this competition!";
                return View(competitionScore);
            }
            else
            {
                //in case of the need to return to Create.cshtml view
                //ViewData["CompetitionID"] = GetCompetitions();
                if (ModelState.IsValid)
                {
                    //Add competition score record to database
                    int count = competitionScoreContext.Add(competitionScore);
                    //Redirect user to CompetitionScore/Index view
                    return RedirectToAction("Index");
                }
                else
                {
                    //Input validation fails, return to the Create view
                    //to display error message
                    return View(competitionScore);
                }
            }
        }
        private List<SelectListItem> GetRemainingCriterias(int comp, int comid)
        {
            List<CompetitionScore> competitionScores = competitionScoreContext.GetCompetitorScores(comp, comid);
            List<SelectListItem> remainingCriterias = new List<SelectListItem>();
            foreach (CompetitionScore cs in competitionScores)
            {
                bool t = true;
                foreach (Criteria cri in GetCriterias(comp))
                {
                    if (cs.CriteriaID == cri.CriteriaID)
                    {
                        t = false;
                    }
                }
                if (t == true)
                {
                    remainingCriterias.Add(new SelectListItem
                    {
                        Value = cs.CriteriaID.ToString(),
                        Text = cs.CriteriaID.ToString()
                    });
                }
            }
            return remainingCriterias;
        }

        private List<Criteria> GetCriterias(int competitionID)
        {
            List<Criteria> criterias = new List<Criteria>();
            foreach (Criteria criteria in criteriaContext.GetAllCriteria())
            {
                if (criteria.CompetitionID == competitionID)
                {
                    criterias.Add(new Criteria
                    {
                        CriteriaID = criteria.CriteriaID,
                        CriteriaName = criteria.CriteriaName
                    });
                }
            }
            return criterias;
        }

        // GET: CompetitionScore/Edit/5
        public ActionResult Edit(int? critid, int? compid, int? comid)
        {
            // Stop accessing the action if not logged in
            // or account not in the "Judge" role
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Judge"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (critid == null)
            { //Query string parameter not provided
              //Return to listing page, not allowed to edit
                return RedirectToAction("Index");
            }
            CompetitionScore competitionScore = competitionScoreContext.GetCompetitorScoreDetails(compid.Value, comid.Value, critid.Value);
            if (competitionScore == null)
            {
                //Return to listing page, not allowed to edit
                return RedirectToAction("Index");
            }
            return View(competitionScore);
        }

        // POST: CompetitionScore/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CompetitionScore competitionScore)
        {
            if (competitionContext.GetDetails(competitionScore.CompetitionID).ResultReleasedDate < DateTime.Now)
            {
                TempData["CompScoreEditErrorMessage"] = "Results have already been released for this competition!";
                return View(competitionScore);
            }
            else
            {
                if (ModelState.IsValid)
                {
                    //Update competition score record to database
                    competitionScoreContext.Update(competitionScore);
                    return RedirectToAction("Index");
                }
                else
                {
                    //Input validation fails, return to the view
                    //to display error message
                    return View(competitionScore);
                }
            }
        }

        // GET: CompetitionScore/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CompetitionScore/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

WEB2021Apr_P04_T6/Views/CompetitionScore/Create.cshtml
@model WEB2021Apr_P04_T6.Models.CompetitionScore

@{
    ViewData["Title"] = "Set Score";
}

<h4 class="PageTitle">Set/Edit Score</h4>
<hr />
<form asp-action="Create">
    <fieldset class="FormContent">
        <div class="form-group row">
            <label asp-for="CriteriaID"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-4">
                <select asp-for="CriteriaID"
                        asp-items="@ViewData["CriteriaID"]
 as List<SelectListItem>"
                        class="form-control"></select>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="CompetitorID"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="CompetitorID" readonly
                       class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="CompetitionID"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="CompetitionID" readonly
                       class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Score"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="Score" class="form-control" />
                <span asp-validation-for="Score"
                      class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Save"
                       class="btn btn-primary" />
            </div>
        </div>
        <div class="col-sm-9 offset-sm-3">
            <span style="color:red;">@TempData["CompScoreCreateErrorMessage"]</span>
        </div>
        <div>
            <a asp-action="Index">Back to List</a>
        </div>
    </fieldset>
</form>

WEB2021Apr_P04_T6/Views/CompetitionScore/Edit.cshtml
@model WEB2021Apr_P04_T6.Models.CompetitionScore

@{
    ViewData["Title"] = "Edit Score";
}

<h4 class="PageTitle">Set/Edit Score</h4>
<hr />
<form asp-action="Edit">
    <fieldset class="FormContent">
        <div class="form-group row">
            <label asp-for="CriteriaID"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="CriteriaID" readonly
                       class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="CompetitorID"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="CompetitorID" readonly
                       class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="CompetitionID"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="CompetitionID" readonly
                       class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Score"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="Score" class="form-control" />
                <span asp-validation-for="Score"
                      class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Save"
                       class="btn btn-primary" />
            </div>
        </div>
        <div class="col-sm-9 offset-sm-3">
            <span style="color:red;">@TempData["CompScoreEditErrorMessage"]</span>
        </div>
        <div>
            <a asp-action="Index">Back to List</a>
        </div>
    </fieldset>
</form>

WEB2021Apr_P04_T6/Views/CompetitionScore/Index.cshtml
@model WEB2021Apr_P04_T6.Models.SubmissionScoreViewModel

<div class="table-responsive">
    <table id="viewCompetitionSubmission" class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>CompetitionID</th>
                <th>CompetitorID</th>
                <th>Name</th>
                <th>FileUpload</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.submissionList)
            {
                string selectedRow = "";
                if (ViewData["selectedCompetitor"].ToString()
                 == item.CompetitorID.ToString())
                {
                    // Highlight the selected row
                    selectedRow = "class='table-primary'";
                }
                <tr @Html.Raw(selectedRow)>
                    <td>@item.CompetitionID.ToString()</td>
                    <td>@item.CompetitorID.ToString()</td>
                    <td>@item.</td>
                    <td>@item.FileSubmitted.ToString()</td>
                    <td>
                        <a asp-action="Index" asp-controller="CompetitionScore"
                           asp-route-id="@item.CompetitorID" asp-route-compid="@item.CompetitionID">View Scores</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<!-- Display a list of staff members for each branch -->
@if (ViewData["selectedCompetitor"].ToString() != "")
{
    if (Model.scoreList.Count != 0)
    {
        <h5>
            Scores for
            @ViewData["selectedCompetitor"].ToString() :
        </h5>
        <p><a asp-action="Create" asp-route-id="@ViewData["selectedCompetitor"].ToString()"
              asp-route-comp="@ViewData["selectedCompetition"].ToString()" >Set New Score</a></p>
        <partial name="~/Views/CompetitionScore/_ViewCompetitionScore.cshtml"
                 model="@Model.scoreList" />
    }
    else
    {
        <h5>No scores for selected competitor!</h5>
    }
}

WEB2021Apr_P04_T6/Views/CompetitionScore/_ViewCompetitionScore.cshtml
@model IEnumerable<WEB2021Apr_P04_T6.Models.CompetitionScore>

@if (Model.ToList().Count > 0)
{
<div class="table-responsive">
    <table id="viewCompetitionScore" class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>CriteriaID</th>
                <th>CompetitorID</th>
                <th>CompetitionID</th>
                <th>Score</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
                {
            <tr>
                <td>@item.CriteriaID.ToString()</td>
                <td>@item.CompetitorID.ToString()</td>
                <td>@item.CompetitionID.ToString()</td>
                <td>@item.Score.ToString()</td>
                <td>
                    <a asp-action="Edit" asp-controller="CompetitionScore" asp-route-critid="@item.CriteriaID"
                       asp-route-compid="@item.CompetitionID" asp-route-comid="@item.CompetitorID">Edit Score</a>
                </td>
            </tr>
                }
        </tbody>
    </table>
</div>
}
else
{
<span style="color:red">No Competition Score record found!</span>
}