WEB2021Apr_P04_T6/Models/Competition.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WEB2021Apr_P04_T6.Models
{
    public class Competition
    {
        public int CompetitionID { get; set; }
        [Required]
        [Display(Name = "Area of Interest")]
        public int AreaInterestID { get; set; }
        [Required]
        [Display(Name = "Competition Name")]
        [StringLength(255, ErrorMessage = "Name cannot exceed 255 characters.")]
        public string CompetitionName { get; set; }
        [Display(Name = "Start Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime StartDate { get; set; }
        [Display(Name = "End Date")]
        // checking if end date is later than start date
        [ValidateDate("StartDate")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime EndDate { get; set; }
        [Display(Name = "Results Date")]
        // checking if results date is later than end date
        [ValidateDate("EndDate")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime ResultReleasedDate { get; set; }
        [Display(Name = "Judges")]
        // judges displayed below as checkboxes for user to select
        public List<Judges> Judges { get; set; }
    }

    // this is used for adding of judges when creating competitions
    public class Judges
    {
        public string Name { get; set; }
        public bool Selected { get; set; }
    }

    public class CompetitionViewModel
    {
        public int CompetitionID { get; set; }

        public DateTime StartDate { get; set; }

        public string CompetitionName { get; set; }

        public int? CompetitorID { get; set; }
        public string FileSubmitted { get; set; }


    }


    public class CompetitionScoreViewModel
    {

        public string CompetitionName { get; set; }

        public int Score { get; set; }


    }
}

WEB2021Apr_P04_T6/Models/CompetitionViewmodel.cs
sing System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WEB2021Apr_P04_T6.Models
{
    public class CompetitionViewmodel
    {
    }
}

WEB2021Apr_P04_T6/Controllers/CompetitionController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WEB2021Apr_P04_T6.DAL;
using WEB2021Apr_P04_T6.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WEB2021Apr_P04_T6.Controllers
{
    public class CompetitionController : Controller
    {
        private Competition competition1 = new Competition();
        private CompetitionDAL competitionContext = new CompetitionDAL();
        private AreaInterestDAL areaInterestContext = new AreaInterestDAL();
        private JudgeDAL judgeContext = new JudgeDAL();
        // GET: AreaInterestController
        public ActionResult Index()
        {
            List<Competition> competitionList = competitionContext.GetAllCompetitions();
            return View(competitionList);
        }

        // GET: AreaInterestController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: AreaInterestController/Create
        public ActionResult Create()
        {
            // Stop accessing the action if not logged in
            // or account not in the admin role
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Administrator"))
            {
                return RedirectToAction("Index", "Home");
            }

            ViewData["AreaInterestList"] = GetAreaInterests();
            competition1.Judges = GetJudges();
            return View(competition1);
        }
        // POST: AreaInterestController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Competition competition)
        {
            ViewData["AreaInterestList"] = GetAreaInterests();
            if (ModelState.IsValid)
            {
                // Add competition record to database
                competition.CompetitionID = competitionContext.AddCompetition(competition);
                competition1.Judges = GetJudges();
                // get competitionjudge list to pass values from judges selected from create competition page
                List<CompetitionJudge> compJudgeList = new List<CompetitionJudge>();
                foreach (Judges j in competition1.Judges)
                {
                    if (j.Selected == true)
                    {
                        // judges that were ticked on the checkbox
                        // add them into competitionjudge list
                        compJudgeList.Add(new CompetitionJudge
                        {
                            // pass values in
                            CompetitionID = competition.CompetitionID
                            // i could not find a way to pass judgeID into the list, which ultimately made adding records not work
                        });
                    }
                }
                // loop through each competitionjudge
                foreach (CompetitionJudge cj in compJudgeList)
                {
                    // add into database
                    competition.CompetitionID = competitionContext.AddJudge(cj);
                }
                // Redirect user to Index view
                return RedirectToAction("Index");
            }
            else
            {
                // Input validation fails, return to the Create view
                // to display error message
                return View(competition);
            }
        }
        // GET: AreaInterestController/Edit/5
        public ActionResult Edit(int? id)
        {
            // Stop accessing the action if not logged in
            // or account not in the admin role
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Administrator"))
            {
                return RedirectToAction("Index", "Home");
            }

            if (id == null)
            { //Query string parameter not provided
              //Return to listing page, not allowed to edit
                return RedirectToAction("Index");
            }

            ViewData["AreaInterestList"] = GetAllAreaInterests();
            Competition competition = competitionContext.GetDetails(id.Value);
            if (competition == null)
            {
                //Return to listing page, not allowed to edit
                return RedirectToAction("Index");
            }
            return View(competition);
        }

        // POST: AreaInterestController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Competition competition)
        {
            ViewData["AreaInterestList"] = GetAllAreaInterests();
            if (ModelState.IsValid)
            {
                if (!competitionContext.GetCompetitors(competition.CompetitionID).Any())
                {
                    // Competitor doesn't exist, then
                    // update competition record to database
                    competitionContext.Update(competition);
                }
                return RedirectToAction("Index");
            }
            else
            {
                //Input validation fails, return to the view
                //to display error message
                return View(competition);
            }
        }

        // GET: AreaInterestController/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                //Return to listing page, not allowed to edit
                return RedirectToAction("Index");
            }
            Competition competition = competitionContext.GetDetails(id.Value);
            if (competition == null)
            {
                //Return to listing page, not allowed to edit
                return RedirectToAction("Index");
            }
            return View(competition);
        }

        // POST: AreaInterestController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Competition competition)
        {
            if (!competitionContext.GetSelectedCompetitionJudges(competition.CompetitionID).Any() && (!competitionContext.GetCompetitors(competition.CompetitionID).Any()))
            {
                // Competitor and CompetitionJudge doesn't exist, then
                // delete the competition record from database
                competitionContext.Delete(competition.CompetitionID);
            }
            // else return to index page
            return RedirectToAction("Index");
        }
        private List<SelectListItem> GetAreaInterests()
        {
            List<SelectListItem> aoi = new List<SelectListItem>();
            foreach (AreaInterest areaInterest in areaInterestContext.GetAllAreaInterests())
            {
                aoi.Add(new SelectListItem
                {
                    Value = areaInterest.AreaInterestID.ToString(),
                    Text = areaInterest.Name
                });
            }
            return aoi;
        }
        private List<AreaInterest> GetAllAreaInterests()
        {
            // Get a list of branches from database
            List<AreaInterest> aoiList = areaInterestContext.GetAllAreaInterests();
            // Adding a select prompt at the first row of the branch list
            aoiList.Insert(0, new AreaInterest
            {
                AreaInterestID = 0,
                Name = "--Select--"
            });
            return aoiList;
        }
        public List<Judges> GetJudges()
        {
            List<Judges> judgeList = new List<Judges>();
            foreach (Judge judge in judgeContext.GetAllJudges())
            {
                judgeList.Add(new Judges
                {
                    Name = judge.Name,
                    Selected = false
                });
            }
            return judgeList;
        }
    }
}

WEB2021Apr_P04_T6/Views/Competition/Create.cshtml
@model WEB2021Apr_P04_T6.Models.Competition

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Competition</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group row">
                <label asp-for="CompetitionName"
                       class="col-sm-3 col-form-label"></label>
                <div class="col-sm-9 col-md-5">
                    <input asp-for="CompetitionName" class="form-control" />
                    <span asp-validation-for="CompetitionName"
                          class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="AreaInterestID" class="col-sm-3 col-form-label"></label>
                <div class="col-sm-9 col-md-5">
                    <select asp-for="AreaInterestID"
                            asp-items="@ViewData["AreaInterestList"]
 as List<SelectListItem>"
                            class="form-control">
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="StartDate"
                       class="col-sm-3 col-form-label"></label>
                <div class="col-sm-9 col-md-5">
                    <input asp-for="StartDate" class="form-control" />
                    <span asp-validation-for="StartDate"
                          class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="EndDate"
                       class="col-sm-3 col-form-label"></label>
                <div class="col-sm-9 col-md-5">
                    <input asp-for="EndDate" class="form-control" />
                    <span asp-validation-for="EndDate"
                          class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="ResultReleasedDate"
                       class="col-sm-3 col-form-label"></label>
                <div class="col-sm-9 col-md-5">
                    <input asp-for="ResultReleasedDate" class="form-control" />
                    <span asp-validation-for="ResultReleasedDate"
                          class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WEB2021Apr_P04_T6/Views/Competition/Delete.cshtml
@model WEB2021Apr_P04_T6.Models.Competition

@{
    ViewData["Title"] = "Delete";
}

<h4 class="PageTitle">Delete Competition</h4>
<hr />
<form asp-action="Delete">
    <fieldset class="FormContent">
        <legend>Are you sure to delete this record?</legend>
        <div class="form-group row">
            <label asp-for="CompetitionID"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="CompetitionID" readonly
                       class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="CompetitionName"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="CompetitionName" readonly
                       class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Delete"
                       class="btn btn-primary" />
            </div>
        </div>
        <div>
            <a asp-action="Index">Back to List</a>
        </div>
    </fieldset>
</form>

WEB2021Apr_P04_T6/Views/Competition/Edit.cshtml
@model WEB2021Apr_P04_T6.Models.Competition

@{
    ViewData["Title"] = "Edit";
}

<h4 class="PageTitle">Edit Competition Details</h4>
<hr />
<form asp-action="Edit">
    <fieldset class="FormContent">
        <div class="form-group row">
            <label asp-for="CompetitionID"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="CompetitionID" readonly
                       class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="AreaInterestID"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <select asp-for="AreaInterestID"
                        asp-items="@(new SelectList(
 @ViewData["AreaInterestList"] as List <AreaInterest>,
 "AreaInterestID", "Name"))"
                        class="form-control"></select>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="CompetitionName"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="CompetitionName" readonly
                       class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="StartDate"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate"
                      class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="EndDate"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate"
                      class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="ResultReleasedDate"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="ResultReleasedDate" class="form-control" />
                <span asp-validation-for="ResultReleasedDate"
                      class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Save"
                       class="btn btn-primary" />
            </div>
        </div>
        <div>
            <a asp-action="Index">Back to List</a>
        </div>
    </fieldset>
</form>

WEB2021Apr_P04_T6/Views/Competition/Index.cshtml
@model IEnumerable<WEB2021Apr_P04_T6.Models.Competition>

<h4 class="PageTitle">View Competitions</h4>
<p><a asp-action="Create">Create New</a></p>
<!-- Add a partial view to display a list of staff records
 in a tabular format. -->
<partial name="~/Views/Competition/_ViewCompetition.cshtml" model="@Model" />

WEB2021Apr_P04_T6/Views/Competition/_ViewCompetition.cshtml
@model IEnumerable<WEB2021Apr_P04_T6.Models.Competition>

@if (Model.ToList().Count > 0)
{
    <div class="table-responsive">
        <table id="viewStaff" class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>CompetitionID</th>
                    <th>AreaInterestID</th>
                    <th>Name</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                    <th>Results Release Date</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td>@item.CompetitionID.ToString()</td>
                    <td>@item.AreaInterestID.ToString()</td>
                    <td>@item.CompetitionName</td>
                    <td>@item.StartDate.ToString()</td>
                    <td>@item.EndDate.ToString()</td>
                    <td>@item.ResultReleasedDate.ToString()</td>
                    <td>
                        <a asp-action="Edit" asp-controller="Competition"
                           asp-route-id="@item.CompetitionID">Edit</a> |
                        <a asp-action="Delete" asp-controller="Competition"
                           asp-route-id="@item.CompetitionID">Delete</a>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <span style="color:red">No record found!</span>
}