WEB2021Apr_P04_T6/Controllers/ViewProfileController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WEB2021Apr_P04_T6.DAL;
using WEB2021Apr_P04_T6.Models;

namespace WEB2021Apr_P04_T6.Controllers
{
    public class ViewProfileController : Controller
    {
        private CompetitionDAL competitionContext = new CompetitionDAL();
        private CompetitorDAL competitorContext = new CompetitorDAL();


        public ActionResult Create()
        {
            ViewData["Salutation"] = GetSalutations();

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Competitor Competitor)
        {
            ViewData["Salutation"] = GetSalutations();
            if (ModelState.IsValid)
            {
                //Add criteria record to database
                Competitor.CompetitorID = competitorContext.Add(Competitor);
                //Redirect user to Judge/Index view
                TempData["CompetitorMessage"] = "Competitor Profile successfully created";
                return RedirectToAction("Create");
            }
            return View();
        }

        public List<SelectListItem> GetSalutations()
        {
            List<SelectListItem> salutations = new List<SelectListItem>();
            salutations.Add(new SelectListItem
            {
                Value = "Mr",
                Text = "Mr"
            });
            salutations.Add(new SelectListItem
            {
                Value = "Ms",
                Text = "Ms"
            });
            salutations.Add(new SelectListItem
            {
                Value = "Mrs",
                Text = "Mrs"
            });
            salutations.Add(new SelectListItem
            {
                Value = "Mdm",
                Text = "Mdm"
            });
            salutations.Add(new SelectListItem
            {
                Value = "Dr",
                Text = "Dr"
            });
            return salutations;
        }
    }
}

WEB2021Apr_P04_T6/Views/ViewProfile/Create.cshtml
@model WEB2021Apr_P04_T6.Models.Competitor

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h1>Create Profile</h1>
<form asp-action="Create" asp-controller="ViewProfile" method="post">
    <fieldset class="FormContent">
        <div class="form-group row">
            <label asp-for="CompetitorName"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="CompetitorName" class="form-control" />
                <span asp-validation-for="CompetitorName"
                      class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Salutation"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-4">
                <select asp-for="Salutation"
                        asp-items="@ViewData["Salutation"]
                        as List<SelectListItem>"
                        class="form-control"></select>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="EmailAddr"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="EmailAddr" class="form-control" type="email" />
                <span asp-validation-for="EmailAddr"
                      class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Password"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="Password" class="form-control" type="password" />
                <span asp-validation-for="Password"
                      class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Create"
                       class="btn btn-primary" />
            </div>
        </div>
        <div class="col-sm-9 offset-sm-3">
            <span style="color:red;">@TempData["CompetitorMessage"]</span>
        </div>
    </fieldset>
</form>