WEB2021Apr_P04_T6/Models/AreaInterest.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WEB2021Apr_P04_T6.Models
{
    public class AreaInterest
    {
        public int AreaInterestID { get; set; }
        [Required]
        [Display(Name = "Area of Interest")]
        [StringLength(50)]
        [ValidateAOIExists]
        public string Name { get; set; }
    }
}

WEB2021Apr_P04_T6/Controllers/AreaInterestController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WEB2021Apr_P04_T6.DAL;
using WEB2021Apr_P04_T6.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Data.SqlClient;

namespace WEB2021Apr_P04_T6.Controllers
{
    public class AreaInterestController : Controller
    {
        private AreaInterestDAL areaInterestContext = new AreaInterestDAL();

        // GET: AreaInterestController
        public ActionResult Index()
        {
            List<AreaInterest> areaInterestList = areaInterestContext.GetAllAreaInterests();
            return View(areaInterestList);
        }

        // GET: AreaInterestController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: AreaInterestController/Create
        public ActionResult Create(int id)
        {
            // Stop accessing the action if not logged in
            // or account not in the admin role
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Administrator"))
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        // POST: AreaInterestController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AreaInterest areaInterest)
        {
            if (ModelState.IsValid)
            {
                //Add aoi record to database
                areaInterest.AreaInterestID = areaInterestContext.Add(areaInterest);
                //Redirect user to index view
                return RedirectToAction("Index");
            }
            else
            {
                //Input validation fails, return to the Create view
                //to display error message
                return View(areaInterest);
            }
        }

        // GET: AreaInterestController/Edit/5
        public ActionResult Edit(int id)
        {
            // Stop accessing the action if not logged in
            // or account not in the admin role
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Administrator"))
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        // POST: AreaInterestController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AreaInterestController/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                //Return to listing page, not allowed to delete
                return RedirectToAction("Index");
            }
            AreaInterest aoi = areaInterestContext.GetDetails(id.Value);
            if (aoi == null)
            {
                //Return to listing page, not allowed to delete
                return RedirectToAction("Index");
            }
            return View(aoi);
        }

        // POST: AreaInterestController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(AreaInterest aoi)
        {
            if (!areaInterestContext.GetAllCompetitions(aoi.AreaInterestID).Any())
            {
                // competition doesn't exist, then
                // delete the aoi record from database
                areaInterestContext.Delete(aoi.AreaInterestID);
            }
            return RedirectToAction("Index");
        }
    }
}

WEB2021Apr_P04_T6/Views/AreaInterest/Create.cshtml
@model WEB2021Apr_P04_T6.Models.AreaInterest

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Area of Interest</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WEB2021Apr_P04_T6/Views/AreaInterest/Delete.cshtml
@model WEB2021Apr_P04_T6.Models.AreaInterest

@{
    ViewData["Title"] = "Delete";
}

<h4 class="PageTitle">Delete Staff Record</h4>
<hr />
<form asp-action="Delete">
    <fieldset class="FormContent">
        <legend>Are you sure to delete this record?</legend>
        <div class="form-group row">
            <label asp-for="AreaInterestID"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="AreaInterestID" readonly
                       class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Name"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="Name" readonly
                       class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Delete"
                       class="btn btn-primary" />
            </div>
        </div>
        <div>
            <a asp-action="Index">Back to List</a>
        </div>
    </fieldset>
</form>

WEB2021Apr_P04_T6/Views/AreaInterest/Index.cshtml
@model IEnumerable<WEB2021Apr_P04_T6.Models.AreaInterest>

<h4 class="PageTitle">View Area of Interests</h4>
<p><a asp-action="Create">Create New</a></p>
<!-- Add a partial view to display a list of staff records
 in a tabular format. -->
<partial name="~/Views/AreaInterest/_ViewAreaInterest.cshtml" model="@Model" />

WEB2021Apr_P04_T6/Views/AreaInterest/_ViewAreaInterest.cshtml
@model IEnumerable<WEB2021Apr_P04_T6.Models.AreaInterest>

@if (Model.ToList().Count > 0)
{
    <div class="table-responsive">
        <table id="viewStaff" class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.AreaInterestID.ToString()</td>
                        <td>@item.Name</td>
                        <td>
                            <a asp-action="Delete" asp-controller="AreaInterest"
                               asp-route-id="@item.AreaInterestID">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <span style="color:red">No record found!</span>
}